apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.31.165/smb-share"
  # subDir: "music"  # Chỉ mount thư mục "music"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "development"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "development"
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0775
  - file_mode=0775