---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-navidrome-smb
  namespace: development
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-navidrome-smb
  storageClassName: smb